# model 均为本地模型权重的路径
models:
  - model: /mnt/zjy/model_merging/mergekit/optimization/ckpts/Interfuser/taskA/other_weights.pth
    parameters:
      density: 1
      weight: 0.5
  - model: /mnt/zjy/model_merging/mergekit/optimization/ckpts/Interfuser/taskB/other_weights.pth
    parameters:
      density: 1
      weight: 0.5
merge_method: ties
base_model: /mnt/zjy/model_merging/mergekit/optimization/ckpts/Interfuser/base/other_weights.pth
parameters:
  normalize: true
dtype: bfloat16