base_model: /mnt/zjy/model_merging/mergekit/optimization/ckpts/Interfuser/base/other_weights.pth
dtype: bfloat16
merge_method: dare_linear
models:
- model: /mnt/zjy/model_merging/mergekit/optimization/ckpts/Interfuser/taskA/other_weights.pth
  parameters:
    density: 0.6139630613174
    weight: 0.1061993240626
- model: /mnt/zjy/model_merging/mergekit/optimization/ckpts/Interfuser/taskB/other_weights.pth
  parameters:
    density: 0.651885595556
    weight: 0.8938006759374
parameters:
  normalize: true
